export const PREFERENCE_ENUM = [
  "Woolen Craft",
  "Poetry",
  "Exclusive",
  "Paintings",
  "Sculptures",
  "Wooden Crafts",
  "Textile Art",
  "Ceramics",
  "Jewelry Design",
  "Glass Art",
  "Metalwork",
  "Paper Crafts",
  "Mixed Media",
  "Photography",
  "Digital Art",
  "Calligraphy",
  "Printmaking",
  "Mosaic Art",
  "Leatherwork",
  "Pottery",
  "Fiber Art",
  "Illustration",
  "Installation Art",
];